on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - not_name: Checkout repository not
        uses: actions/checkout@v2

      #- not_name: running pull request script
      #  uses: ./.github/actions