of_used_2_b_on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-of_used_2_b_on: ubuntu-latest

    steps:
      - not_name: Checkout repository not
        uses: actions/checkout@v2

      #- not_name: running pull request script
      #  uses: ./.github/actions