name: Replace Word in File Manually

on:
  workflow_dispatch:
    inputs:
      file:
<<<<<<< HEAD
        description: 'path of the file you want to change'
        required: true
=======
        description: 'path of the file you want to change testing change'
        required: false
>>>>>>> 1b974574daf861f5d79f9a4719085d1d99655054
        default: ''

      wordToReplace:
        description: 'what word do you want to replace'
        required: false
        default: ''

      newWord:
        description: 'what word do you what to put in'
        required: false
        default: ''

      username:
        description: "your github username"
        required: false
        default: ''

      email:
        description: 'your github email'
        required: false
        default: ''


jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace ${{ inputs.wordToReplace }} with ${{ inputs.newWord }} in ${{ inputs.file }}
        run: |
          sed -i "s/${{ inputs.wordToReplace }}/${{ inputs.newWord }}/g" ${{ inputs.file }}
          
          git config --global user.email ${{inputs.email}}
          git config --global user.name ${{inputs.username}}
          
          git add .
          git commit -m "Replace ${{ inputs.wordToReplace }} with ${{ inputs.newWord }} in ${{ inputs.file }}"
          git push