name: Replace Word in File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'file you want to change'
        required: true
        default: ''

      wordToReplace:
        description: 'what word do you want to replace'
        required: true
        default: ''

      newWord:
        description: 'what word do you what to put in'
        required: true
        default: ''


  push:
    branches:
      - main

jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace ${{ inputs.wordToReplace }} with ${{ inputs.newWord }} in ${{ inputs.file }} by ${{ github.event.inputs.username }} | ${{ github.event.inputs.email }}
        run: |
          sed -i "s/\<${{ inputs.wordToReplace }}\>/${{ inputs.newWord }}/g" ${{ inputs.file }}
          git config --global user.email ${{ github.event.inputs.email }}
          git config --global user.name ${{ github.event.inputs.username }}

          git add .
          git commit -m "Replace ${{ inputs.wordToReplace }} with ${{ inputs.newWord }} in ${{ inputs.file }}"
          git push
