name: Replace Word in File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'file you want to change'
        required: true
        default: ''

      wordToReplace:
        description: 'what word do you want to replace'
        required: true
        default: ''

      newWord:
        description: 'what word do you what to put in'
        required: true
        default: ''

      username:
        description: "your github username"
        required: true
        default: ''

      email:
        description: 'your github email'
        required: true
        default: ''

  push:
    branches:
      - main

jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace ${{ inputs.wordToReplace }} with ${{ inputs.newWord }} in ${{ inputs.file }}
        run: |
          node index.js ${{ github.event.inputs.file }} ${{ github.event.inputs.wordToReplace }} ${{ github.event.inputs.newWord }} ${{ github.event.inputs.username }} ${{ github.event.inputs.email }}
        
