name: Replace Word in File

on:
  workflow_dispatch:
    inputs:
      file:
        description: 'file you want to change'
        required: true
        default: ''

      wordToReplace:
        description: 'what word do you want to replace'
        required: true
        default: ''

      newWord:
        description: 'what word do you what to put in'
        required: true
        default: ''

      username:
        description: "your github username"
        required: true
        default: ''

      email:
        description: 'your github email'
        required: true
        default: ''


jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Split newWords into an array
        id: split_words
        run: |
          IFS=',' read -r -a WORDS_ARRAY <<< "${{ inputs.newWords }}"
          echo "::set-output name=words::${WORDS_ARRAY[*]}"


      - name: Replace ${{ inputs.wordToReplace }} with ${{ inputs.newWord }} in ${{ inputs.file }}
        run: |
          for word in "${{ steps.split_words.outputs.words }}"; do
            sed -i "s/${{ inputs.wordToReplace }}/$word/g" ${{ inputs.file }}
          done
          
          git config --global user.email ${{inputs.email}}
          git config --global user.name ${{inputs.username}}
          git add .
          git commit -m "Replace ${{ inputs.wordToReplace }} with ${{ inputs.newWord }} in ${{ inputs.file }}"
          git push