name: Replace Word in File

on:
  push:
    branches:
      - main

jobs:
  replace-word:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        wordsToReplace:  
          - or
          - it
          - you

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Replace words in file
        run: |
          for word in ${{ matrix.wordsToReplace }}; do
            sed -i "s/$word/newWord/g" file.txt
          done

      - name: Configure Git
        run: |
          git config --local user.email "fogadm06@gmail.com"
          git config --local user.name "FogadOg"

      - name: Replace Words
        run: |
          git add file.txt
          git commit -m "Replace specified words with 'newWord'"
          git push https://FogadOg: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@github.com/FogadOg/javaSearchEngine.git HEAD:main
