name: Replace Word in File
#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
on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'  # Specify your Python version here

      - name: Replace word in file
        run: |
          sed -i 's/oldWord/newWord/g' file.txt


      - name: Configure Git
        run: |
          git config --local user.email "fogadm06@gmail.com"
          git config --local user.name "FogadOg"

      - name: Replace Word
        run: |
          git add file.txt
          git commit -m "Replace 'old_word' with 'new_word'"
          git push https://FogadOg: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@github.com/FogadOg/javaSearchEngine.git HEAD:main

