name: Replace Word in File

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  replace-word:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        newWords: ["newWord1", "newWord2", "newWord3"]  # Define your 'array' as a string separated by commas

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'  # Specify your Python version here

      - name: Replace word in file
        run: |
          for word in ${{ matrix.newWords }}; do
            sed -i "s/oldWord/${word}/g" file.txt
          done

      - name: Configure Git
        run: |
          git config --local user.email "fogadm06@gmail.com"
          git config --local user.name "FogadOg"

      - name: Replace Word
        run: |
          git add file.txt
          git commit -m "Replace 'oldWord' with '${{ matrix.newWords }}'"
          git push https://FogadOg:<your_personal_access_token>@github.com/FogadOg/javaSearchEngine.git HEAD:main
