name: Replace Words in YAML

on:
  push:
    branches:
      - main


jobs:
  replace-words:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace words in YAML
        run: |
          sed -i "s/repository/newWord/g" config.yml

      - name: Display File Contents After Replacement
        run: cat config.yml
