name: Replace Words in YAML

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Replace Text in Workflow
        run: |
          sed -i 's/This is the line you want to change/This is the updated line/' config.yml
