name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run My Custom Action
        run: sed -i 's/color/colour/g' ././github/actions/config.yml
        # uses: ./.github/actions

