name: My Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "javaSearchEngine"
          replace: "world"
          include: "**README.md"
          debug: true  # Add this line for more verbose output

