name: Replace Word in File

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      file:
        description: 'file you want to change'
        required: true
        default: ''
      wordToReplace:
        description: 'what word do you want to replace'
        required: true
        default: ''
      newWord:
        description: 'what word do you what to put in'
        required: true
        default: ''

jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace word in file.txt
        run: |
          sed -i "s/${{ inputs.wordToReplace }}/${{ inputs.newWord }}/g" ${{ inputs.file }}
