name: Replace Word in File

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'  # Specify your Python version here

      - name: Replace Word
        run: |
          python script.py
          git commit -m "Replace 'old_word' with 'new_word'"
          git push
