name: My Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: replace
        uses: Nambers/ReplaceStringInFile@v1
        with:
          path: config.yml
          oldString: repository
          oldStringWin: repository
          newString: --_
          showFileContent: true
