name: Replace Word in File

on:
  push:
    branches:
      - main

jobs:
  replace-word:
    runs-on: ubuntu-latest

    inputs:
      newWord:
        description: 'The new word to put in the file'
        required: true
        


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Replace word in file
        run: |
          sed -i 's/oldWord/${{ inputs.newWord }}/g' file.txt

      - name: Configure Git
        run: |
          git config --local user.email "fogadm06@gmail.com"
          git config --local user.name "FogadOg"

      - name: Replace Word
        run: |
          git add file.txt
          git commit -m "Replace 'oldWord' with '${{ inputs.newWord }}'"
          git push https://FogadOg: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@github.com/FogadOg/javaSearchEngine.git HEAD:main
