name: Replace Words in YAML

on:
  push:
    branches:
      - main


jobs:
  replace-words:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace words in YAML
        run: |
          sed -i "s/Repository/newWord/g" .github/workflows/config.yml


