name: Replace Word in File

on:
  push:
    branches:
      - main # Change this to your branch name

jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Replace Word
        run: |
          npm install # If you have dependencies
          node index.js
