name: CICD

on:
  push:
    branches:
      - master
      - cicd-*
  workflow_dispatch:
    inputs:
      file:
        description: 'file you want to change'
        required: true
        default: ''
      wordToReplace:
        description: 'what word do you want to replace'
        required: true
        default: 'Pre-prod'
      newWord:
        description: 'what word do you what to put in'
        required: true
        default: ''
