name: Replace Word in YAML

on:
  push:
    branches:
      - main

jobs:
  replace-word:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace word in YAML
        run: |
          sed -i 's/Repository/newword/g' config.yml
          # Commit the changes
          git config --global user.email "fogadm06@gmial.com"
          git config --global user.name "fogadOg"
          git add config.yml
          git commit -m "Replace 'reposetory' with 'newword' in example.yml by GitHub Actions"
          git push