name: Replace Words in YAML

on:
  push:
    branches:
      - main


jobs:
  replace-words:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace words in YAML
        run: |
          

          sed -i "s/${main}/${NEW_WORD}/g" ./github/workflows/config.yml
