name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace specific word in file
        run: |
          # Replace 'word_to_replace' with 'replacement_word' in file.txt
          sed -i 's/name/workes/g' ./.github/workflows/config.yml

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Replace specific word in file.txt"
          git push



