name: Execute index.js on push
on:
  push:
    branches:
      - main  # Change this to match your main branch name

jobs:
  execute_index:
    runs-on: ubuntu-latest  # You can change the operating system if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Set the Node.js version you want to use

      - name: Execute index.js
        run: |
          node index.js
