name: Replace Word in File

on:
  workflow_dispatch:
    inputs:
      newWord:
        description: 'New word to replace in the file'
        required: true

jobs:
  replace-word:
    runs-on: ubuntu-latest

    env:
      NEW_WORD: ${{ github.event.inputs.newWord }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.0'

      - name: Replace word in file
        run: |
          sed -i 's/oldWord/'"$NEW_WORD"'/g' file.txt

      - name: Configure Git
        run: |
          git config --local user.email "fogadm06@gmail.com"
          git config --local user.name "FogadOg"

      - name: Replace Word
        run: |
          git add file.txt
          git commit -m "Replace 'oldWord' with '$NEW_WORD'"
          git push https://FogadOg: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@github.com/FogadOg/javaSearchEngine.git HEAD:main
